version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "mnid/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-

      - run: ./gradlew dependencies :demoapp:androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "mnid/build.gradle" }}

      # run tests!
      - run: ./gradlew test jacocoReport

      # store test results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results